### PR TITLE
Added the easy working solution for EXUNA

### PR DESCRIPTION
**Pull request by darkmatter18**
As the PR says:
- Lesser Syntax
- Complexity `O(1)` (Without the sort)
- Easy to understand

Cheers!

### CODE REVIEW

**Comment by darkmatter18** [comment]
@OddExtension5 @chttrjeankr Please review

**Comment by chttrjeankr** [comment]
I'd suggest you make a submission at `https://www.codechef.com/INCF2019/problems/EXUNA`. And if all test cases pass, we can merge your solution.

**Comment by darkmatter18** [comment]
I did that yesterday. They already passed!

**Comment by darkmatter18** [comment]
Thanks @chttrjeankr :)

**Comment by chttrjeankr** [comment]
With reference solution [here](https://www.codechef.com/viewsolution/28060888)

**Pull request merged**
